ignored = [
  "syscall/js"
]

[prune]
  non-go = true
  go-tests = true
  unused-packages = true

[[constraint]]
  branch = "master"
  name = "github.com/vecty-material/material"

[[constraint]]
  branch = "master"
  name = "github.com/gopherjs/vecty"
