ignored = [
  "github.com/gopherjs/gopherwasm/js"
]

[prune]
  non-go = true
  go-tests = true
  unused-packages = true

[[constraint]]
  branch = "master"
  name = "agamigo.io/material"

[[constraint]]
  branch = "master"
  name = "github.com/gopherjs/vecty"
